#!name=PicsArt++
#!desc=By: Me
#!homepage=https://github.com/phong010198/TrollStore-Fools
#!author=Me
#!url=https://raw.githubusercontent.com/phong010198/TrollStore-Fools/refs/heads/main/PicsArt/PicsArt.sgmodule

[Script]

Picsart=type=http-response,pattern=https:\/\/api\.(picsart|meiease)\.c(n|om)\/users\/show\/me\.json,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/phong010198/TrollStore-Fools/refs/heads/main/PicsArt/PicsArt.js

[MITM]

hostname = %APPEND% api.picsart.c*, api.meiease.c*